### ISSUE TITLE
wrong directory address

### ISSUE THREAD

**Issue by amirsharifi97** [matciotola/Lambda-PNN#3]
in Usage part, "!python tiff_mat_conversion.py -m Tiff2Mat -ms /path/to/ms.tif -pan /path/to/ms.tif  -o path/to/file.mat" must be changed to "!python tiff_mat_conversion.py -m Tiff2Mat -ms /path/to/ms.tif -pan /path/to/pan.tif  -o path/to/file.mat"

**Comment by matciotola** [comment]
Fixed. Thank you for being so supportive!
